import Link from "next/link";
import type { DeskNote } from "@/lib/deskNote";

// Morning Desk Note — the night's GLM-authored overnight brief on the Home dashboard.
export default function DeskNote({ note, universe }: { note: DeskNote | null; universe: string }) {
  if (!note || !note.sections.length) return null;
  return (
    <section className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-4">
      <div className="mb-2 flex flex-wrap items-baseline justify-between gap-x-3 gap-y-1">
        <h2 className="text-sm font-semibold">
          Morning Desk Note <span className="font-normal text-[var(--text-4)]">· {note.asOf}</span>
        </h2>
        <span className="text-[10px] uppercase tracking-wide text-[var(--text-4)]">AI brief · descriptive, not advice</span>
      </div>
      {note.tldr && <p className="mb-3 text-sm leading-snug text-[var(--text-2)]">{note.tldr}</p>}
      <div className="space-y-3">
        {note.sections.map((s, i) => (
          <div key={i}>
            <h3 className="mb-1 text-[11px] font-semibold uppercase tracking-wide text-[var(--text-3)]">{s.heading}</h3>
            <ul className="space-y-1">
              {s.bullets.map((b, j) => (
                <li key={j} className="flex gap-2 text-sm text-[var(--text-2)]">
                  <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-[var(--text-4)]" aria-hidden />
                  <span className="leading-snug">
                    {b.text}
                    {b.tickers.map((t) => (
                      <Link
                        key={t}
                        href={`/u/${universe}/stock/${encodeURIComponent(t)}`}
                        className="ml-1.5 font-mono text-xs font-semibold text-[#60a5fa] hover:underline"
                      >
                        {t}
                      </Link>
                    ))}
                  </span>
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
      <p className="mt-3 text-[10px] leading-relaxed text-[var(--text-4)]">
        Generated by an AI model from the night&apos;s movers, filings, options flow and analyst actions — spot-check against the linked sources. Not investment advice.
      </p>
    </section>
  );
}
