import Link from "next/link";
import type { DeskNote, DeskTape, DeskCalendar } from "@/lib/deskNote";
import { fmtFresh } from "@/lib/format";

function Tickers({ tickers, universe }: { tickers: string[]; universe: string }) {
  return (
    <>
      {tickers.map((t) => (
        <Link key={t} href={`/u/${universe}/stock/${encodeURIComponent(t)}`} className="ml-1.5 font-mono text-xs font-semibold text-[var(--accent)] hover:underline">
          {t}
        </Link>
      ))}
    </>
  );
}

// Morning Desk Note — the night's GLM-authored two-layer overnight brief.
export default function DeskNote({ note, universe }: { note: DeskNote | null; universe: string }) {
  if (!note || !note.sections.length) return null;
  // Stamp the note's OWN recency (generatedAt), not note.asOf — asOf is the overnight-filings *window*
  // start ("since Jul 1"), which froze on a stale-looking date even when the brief was rebuilt nightly.
  const fresh = fmtFresh(note.generatedAt);
  const runChip = note.run === "morning" ? { t: "Morning run", c: "#f59e0b" } : note.run === "evening" ? { t: "Evening run", c: "#a78bfa" } : null;
  return (
    <section className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-4">
      <div className="mb-2 flex flex-wrap items-baseline justify-between gap-x-3 gap-y-1">
        <h2 className="text-sm font-semibold">
          Desk Note
          {runChip && <span className="ml-2 rounded px-1.5 py-0.5 text-[10px] font-bold uppercase tracking-wide" style={{ color: runChip.c, background: `color-mix(in oklab, ${runChip.c} 15%, transparent)` }}>{runChip.t}</span>}
          {fresh && <span className="font-normal text-[var(--text-4)]"> · as of {fresh}</span>}
        </h2>
        <span className="text-[10px] uppercase tracking-wide text-[var(--text-4)]">AI brief · research, not advice</span>
      </div>
      {note.tape && <TapeStrip tape={note.tape} universe={universe} />}
      {note.tldr && <p className="mb-4 border-l-2 border-[color-mix(in_srgb,var(--accent)_50%,transparent)] pl-3 text-sm leading-snug text-[var(--text)]">{note.tldr}</p>}

      <div className="space-y-6">
        {note.sections.map((s, i) => (
          <div key={i}>
            {/* Section title — sized as a real header with a rule, so the themes scan at a glance. */}
            <h3 className="border-b border-[var(--divider)] pb-1 text-[17px] font-bold leading-snug text-[var(--text)]">{s.heading}</h3>
            {s.synthesis && <p className="mb-2.5 mt-1.5 text-[13px] italic leading-snug text-[var(--text-3)]">{s.synthesis}</p>}
            <ul className="space-y-3">
              {s.bullets.map((b, j) => (
                <li key={j}>
                  <p className="text-sm font-medium leading-snug text-[var(--text)]">
                    {b.fact}
                    <Tickers tickers={b.tickers} universe={universe} />
                  </p>
                  {b.read && <p className="mt-0.5 text-[13px] leading-snug text-[var(--text-2)]">{b.read}</p>}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>

      {note.calendar && (note.calendar.earnings.length > 0 || note.calendar.binaries.length > 0) && (
        <CalendarBox calendar={note.calendar} universe={universe} />
      )}

      {note.watchToday.length > 0 && (
        <div className="mt-4 rounded-lg border border-[var(--border)] bg-[var(--bg)] p-3">
          <h3 className="mb-1.5 text-[11px] font-semibold uppercase tracking-wide text-[var(--text-3)]">What to watch today</h3>
          <ul className="space-y-1">
            {note.watchToday.map((w, i) => (
              <li key={i} className="flex gap-2 text-[13px] text-[var(--text-2)]">
                <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-[#fbbf24]" aria-hidden />
                <span className="leading-snug">
                  {w.text}
                  <Tickers tickers={w.tickers} universe={universe} />
                </span>
              </li>
            ))}
          </ul>
        </div>
      )}

      <p className="mt-3 text-[10px] leading-relaxed text-[var(--text-4)]">
        The tape strip and calendar are computed directly from the data; the narrative is generated by an AI model from the night&apos;s movers, filings, options flow and analyst actions — a research starting point, spot-check against the linked sources. Not investment advice.
      </p>
    </section>
  );
}

// CODE-BUILT tape strip — cap-weighted S&P 1-day, breadth, big movers, VIX, dealer-gamma regime.
function TapeStrip({ tape, universe }: { tape: DeskTape; universe: string }) {
  const up = "#22c55e", down = "#ef4444";
  const Stat = ({ label, children, title }: { label: string; children: React.ReactNode; title?: string }) => (
    <span className="inline-flex items-baseline gap-1.5 whitespace-nowrap" title={title}>
      <span className="text-[10px] uppercase tracking-wide text-[var(--text-4)]">{label}</span>
      <span className="font-mono text-[13px] font-semibold tabular-nums text-[var(--text)]">{children}</span>
    </span>
  );
  return (
    <div className="mb-3 flex flex-wrap items-center gap-x-5 gap-y-1.5 rounded-lg border border-[var(--border)] bg-[var(--bg)] px-3 py-2">
      {tape.avg1d != null && (
        <Stat label="S&P (cap-wtd)" title="Cap-weighted average 1-day return of the S&P 500 constituents">
          <span style={{ color: tape.avg1d >= 0 ? up : down }}>{tape.avg1d >= 0 ? "+" : ""}{tape.avg1d.toFixed(2)}%</span>
        </Stat>
      )}
      <Stat label="Breadth" title="Advancers vs decliners (1-day)">
        <span style={{ color: up }}>{tape.adv}↑</span> <span style={{ color: down }}>{tape.dec}↓</span>
      </Stat>
      <Stat label="±4% movers" title="Names that moved 4% or more">{tape.big}</Stat>
      {tape.vix != null && <Stat label="VIX" title={`FRED close${tape.vixAsOf ? ` as of ${tape.vixAsOf}` : ""} — lags ~a day`}>{tape.vix.toFixed(1)}</Stat>}
      {tape.gamma.map((g) => (
        <Link key={g.symbol} href={`/u/${universe}/gamma-board`} className="inline-flex items-baseline gap-1.5 whitespace-nowrap hover:opacity-80" title="Dealer gamma regime — short amplifies moves, long dampens (see the Gamma Board)">
          <span className="text-[10px] uppercase tracking-wide text-[var(--text-4)]">{g.symbol} γ</span>
          <span className="rounded px-1 py-0.5 text-[10px] font-bold uppercase" style={{ color: g.regime === "short" ? "#f59e0b" : up, background: `color-mix(in oklab, ${g.regime === "short" ? "#f59e0b" : up} 15%, transparent)` }}>{g.regime}</span>
        </Link>
      ))}
    </div>
  );
}

// CODE-BUILT forward calendar — who reports today/tomorrow + imminent hard binaries.
function CalendarBox({ calendar, universe }: { calendar: DeskCalendar; universe: string }) {
  return (
    <div className="mt-4 rounded-lg border border-[var(--border)] bg-[var(--bg)] p-3">
      <h3 className="mb-1.5 text-[11px] font-semibold uppercase tracking-wide text-[var(--text-3)]">Calendar — next 48h</h3>
      {calendar.earnings.length > 0 && (
        <p className="text-[13px] leading-relaxed text-[var(--text-2)]">
          <span className="text-[var(--text-4)]">Earnings: </span>
          {calendar.earnings.map((e, i) => (
            <span key={e.symbol} className="whitespace-nowrap">
              {i > 0 && <span className="text-[var(--text-4)]"> · </span>}
              <Link href={`/u/${universe}/stock/${encodeURIComponent(e.symbol)}`} className="font-mono font-semibold text-[var(--accent)] hover:underline">{e.symbol}</Link>
              <span className="text-[var(--text-4)]"> {e.when}{e.implied != null ? ` ±${e.implied.toFixed(0)}%` : ""}</span>
            </span>
          ))}
        </p>
      )}
      {calendar.binaries.length > 0 && (
        <p className="mt-1 text-[13px] leading-relaxed text-[var(--text-2)]">
          <span className="text-[var(--text-4)]">Hard binaries: </span>
          {calendar.binaries.map((b, i) => (
            <span key={`${b.ticker}-${b.date}`} className="whitespace-nowrap">
              {i > 0 && <span className="text-[var(--text-4)]"> · </span>}
              <Link href={`/u/${universe}/stock/${encodeURIComponent(b.ticker)}`} className="font-mono font-semibold text-[var(--accent)] hover:underline">{b.ticker}</Link>
              <span className="text-[var(--text-4)]"> {b.label.toLowerCase()} {b.daysTo === 0 ? "today" : b.daysTo === 1 ? "tomorrow" : `in ${b.daysTo}d`}{b.implied != null ? ` ±${b.implied.toFixed(0)}%` : ""}</span>
            </span>
          ))}
        </p>
      )}
    </div>
  );
}
