// Plain-English definitions for the finance jargon scattered across the app. Surfaced via
// <InfoDot term="…"/> next to a label, so a non-specialist (e.g. a new VA) can hover any
// metric and learn what it means. Keep each under ~22 words, no jargon-to-explain-jargon.

export const GLOSSARY: Record<string, string> = {
  // Valuation
  "P/E": "Price ÷ earnings per share — dollars paid for $1 of yearly profit. Lower is cheaper.",
  "Fwd P/E": "P/E using next year's expected earnings instead of the last reported year.",
  "EV/EBITDA": "Enterprise value ÷ core operating profit. A debt-aware valuation multiple; lower is cheaper.",
  "P/S": "Price ÷ sales per share. Useful when a company has little or no profit yet.",
  "P/B": "Price ÷ book value (assets minus liabilities) per share.",
  "PEG": "P/E divided by growth rate — values a stock relative to how fast it's growing.",
  "FCF yield": "Free cash flow ÷ market value. The cash the business throws off, as a % of price.",
  "Discount to history": "How cheap a stock is versus its own typical valuation over the past 10 years.",
  // Quality / fundamentals
  "ROE": "Return on equity — profit as a % of shareholder money. Higher means more efficient.",
  "ROIC": "Return on invested capital — profit vs. all the money (debt + equity) put into the business.",
  "Gross margin": "Sales left after the direct cost of the product, as a % of sales.",
  "Operating margin": "Profit from core operations as a % of sales, before interest and tax.",
  "Beta": "How much the stock moves vs. the market. 1 = moves with it; >1 = more volatile.",
  "Market cap": "Total value of all shares = share price × shares outstanding.",
  "Gross exposure": "Long value + short value (both counted positive) — the total market you're exposed to.",
  "HHI concentration": "Sum of each position's squared weight. Higher = more concentrated; 1/HHI ≈ how many equal-weight names it acts like.",
  "Factor tilt": "How far your book leans toward a style (value, momentum, quality…) vs the market, in standard deviations. +σ = tilted toward it.",
  "Crowding": "How much your holdings move together (average return correlation). High correlation = hidden concentration even across sectors.",
  "Beta-neutral hedge": "The dollar amount of index (SPY) to short (or buy) so the book's market beta nets to zero — leaving only stock-picking risk.",
  // Options
  "IV": "Implied volatility — how much movement the options market is pricing in. Higher = pricier options.",
  "IV rank": "Where today's implied volatility sits vs. its own past year (0–100%). High = options are expensive now.",
  "Vol rank": "Where recent realized volatility sits vs. its own history (a percentile).",
  "Delta": "Roughly the chance an option finishes in-the-money; ~16Δ ≈ a 16% chance.",
  "DTE": "Days to expiration — how long until the option contract expires.",
  "Premium": "The cash the option seller collects (or the buyer pays) up front.",
  "RoR": "Return on risk — the income collected vs. the capital you'd lose if it goes wrong.",
  "POP": "Probability of profit — the modeled odds the trade makes money.",
  "Implied move": "The up-or-down swing options are pricing in around an event like earnings.",
  "Straddle": "Buying a call + put at the same strike — a bet on a big move either direction.",
  "Covered call": "Selling a call against stock you own to collect income, capping the upside.",
  "Cash-secured put": "Selling a put while holding the cash to buy the stock if assigned.",
  // Options — volatility
  "Implied volatility": "How much movement the options market is pricing in, annualized. Higher = pricier options. The market's forecast, not the actual move.",
  "Realized volatility": "How much the stock ACTUALLY moved recently, annualized. Compare to implied vol to see if options are pricing too much or too little.",
  "Expected move": "The up-or-down range options are pricing by an expiry — roughly the at-the-money straddle cost ÷ the share price.",
  "Variance premium": "How much more options charge (implied vol) than the stock actually moves (realized vol). Usually positive — the premium seller's edge.",
  "IV / RV": "Implied vol ÷ realized vol. Above ~1.4 = options look rich (sell premium); near or below 1 = cheap (buy the move).",
  "IV vs HV": "Implied vol (what options price) vs historical/realized vol (what the stock did). IV above HV = a variance premium to sell.",
  "Rich / cheap": "Options priced HIGH (rich → sell premium) or LOW (cheap → buy the move) versus how much the stock actually tends to move.",
  "Skew": "The gap between put and call implied vol. Positive = downside puts cost more — the market pays up for crash protection.",
  "Realized vol cone": "The historical min-to-max range of a stock's realized volatility at each horizon. Where today sits inside it: low = unusually quiet (coiled), high = unusually wild.",
  "Coiled spring": "A stock that's unusually quiet (realized vol near the bottom of its own range, so options are cheap) AND positioned for dealers to amplify the next move — a setup for an outsized break.",
  "Term structure": "How implied vol differs across expiry dates. Front richer than back (backwardation) usually means an event is coming.",
  "Vol crush": "Implied vol collapsing the instant an event (like earnings) passes — the premium a straddle buyer pays and a seller collects.",
  "Term crush": "Front-expiry IV ÷ a later expiry's IV. Above 1 = the near-term is event-inflated and set to crush after the print.",
  "IV-crush scenario": "A what-if: reprice your option the morning after the print as you drag the vol lower and the stock up/down — the buyer's trap, quantified.",
  "Event move": "The move priced for the print ITSELF, after stripping the days of ordinary vol out of the straddle — the market's clean earnings expectation.",
  "PEAD": "Post-earnings drift — the tendency for a stock to keep drifting in the direction of an earnings surprise for days after.",
  "Richness": "Implied earnings move ÷ the stock's average historical earnings move. Above ~1.15× = options rich (sell premium); below ~0.85× = cheap (buy the move).",
  "Historical move": "The stock's average absolute 1-day move on its past earnings reports — what the print usually does, to compare against what options price now.",
  "RS-Ratio": "A sector's price relative to SPY over ~60 trading days, scaled so 100 = in line with the market. Above 100 = outperforming.",
  "RS-Momentum": "The 10-day rate of change of the RS-Ratio. Above 100 = the sector's relative strength is improving; below = deteriorating.",
  "RRG": "Relative Rotation Graph — plots each sector's relative strength (x) against its momentum (y). Sectors tend to rotate clockwise: Improving → Leading → Weakening → Lagging.",
  "PDUFA": "The FDA's target decision date on a drug application (NDA/BLA) — a binary, dated catalyst for the sponsor's stock.",
  "CRL": "Complete Response Letter — the FDA declining to approve an application in its current form; the negative outcome of a PDUFA date.",
  "Guidance": "Management's own forward outlook — the revenue/EPS range it tells the Street to expect for the coming quarter or year. Not an analyst estimate; the company's own number.",
  "Raise / reaffirm / cut": "Whether the latest guide RAISED, held (reaffirmed) or CUT the outlook versus what management said last time — a fast read on business momentum.",
  "Beats its own guide": "How often a company's actual EPS came in at or above the guide it gave a quarter earlier — a track record of whether its guidance is conservative or a stretch.",
  "Sandbagger": "A company that habitually guides low then beats — so its guide is effectively a floor, and a beat into the print is the base case. The opposite is an over-promiser that reliably misses.",
  "Max pain": "The strike where the most options expire worthless. Price can drift toward it near expiry as dealers hedge.",
  "Call wall": "The strike above spot with the most call open interest — can act as a ceiling as dealers hedge around it.",
  "Put wall": "The strike below spot with the most put open interest — can act as a floor / support.",
  "Open interest": "The number of option contracts still outstanding at a strike — a gauge of how deep and liquid it is.",
  "Bid/ask width": "The gap between the buy and sell price — the slippage you pay to get into AND out of a trade. Wide = expensive to trade.",
  "ATM": "At-the-money — the strike closest to the current share price. Its options carry the most time value.",
  "Moneyness": "How far a strike sits from the share price, e.g. +10% = a strike 10% above spot; 0 = at-the-money.",
  "Breakeven": "The share price where an option trade starts making money at expiry (strike ± the premium paid or collected).",
  "Vol surface": "Implied vol mapped across every strike AND expiry at once — the full picture of how a name's options are priced.",
  "Implied distribution": "The full probability distribution of where the stock could land at expiry, backed out of option prices (Breeden–Litzenberger). Not one number — the market's whole picture: the odds of finishing up vs down, and where it prices fat tails.",
  "Catalyst vol": "Options that look cheap into a KNOWN scheduled event (an investor day, capital-markets day) — the straddle isn't pricing the move the stock tends to make around such events.",
  "Implied correlation": "How tightly an index's stocks are expected to move together, backed out of index vs single-name option prices. Low = lots of idiosyncratic movement (dispersion richly priced — sell index vol, buy the components); high = index-like.",
  // Options — structures & greeks
  "Strangle": "A call + put at different out-of-the-money strikes — a cheaper bet on a big move than a straddle.",
  "Iron condor": "Sell a put spread AND a call spread — collect premium if the stock stays inside a range; defined risk.",
  "Calendar spread": "Sell a near-dated option and buy a longer-dated one at the same strike — harvests the faster near-term decay.",
  "Bull put spread": "Sell a put, buy a lower one — a bullish, defined-risk way to collect premium.",
  "Bear call spread": "Sell a call, buy a higher one — a bearish, defined-risk way to collect premium.",
  "Risk reversal": "Sell a put and buy a call (or vice-versa) — a cheap, leveraged directional bet that uses the skew.",
  "Vega": "How much an option's price moves for a 1-point change in implied volatility — your exposure to vol.",
  "Theta": "How much an option loses per day just from time passing — the decay a seller collects and a buyer pays.",
  "Gamma": "How fast an option's delta changes as the stock moves — largest near expiry and at-the-money.",
  "Gamma exposure": "GEX — the dollars of stock dealers must trade to stay hedged for a 1% move. Net long gamma → dealers buy dips / sell rips (they dampen and pin vol); net short gamma → they chase the move (amplifying it).",
  "Gamma flip": "The price where dealers flip from net long gamma (they stabilize) to net short gamma (they amplify moves). Above it tends to be calmer / pinned; below it, choppier and trendier.",
  "Put/call ratio": "Put open interest ÷ call open interest — a rough gauge of hedging / bearish positioning; above 1 = more puts than calls outstanding.",
  "Cushion": "How far the stock can fall before a sold put would be assigned — the margin of safety on the premium.",
  "Annualized yield": "A trade's premium expressed as a yearly % return, so setups of different lengths compare fairly.",
  "ITM": "In-the-money — an option with intrinsic value (a call below spot, a put above).",
  "OTM": "Out-of-the-money — an option with only time value, no intrinsic value yet.",
  "Assignment": "When a short option is exercised against you and you must buy (short put) or sell (short call) the stock.",
  "BMO / AMC": "Before market open / after market close — when a company reports, which decides the session the move lands in.",
  // Fund / ownership / market structure
  "NAV": "Net asset value — what a fund's holdings are actually worth per share.",
  "Discount to NAV": "A fund trading below the value of what it holds — you buy $1 of assets for less.",
  "13F": "Quarterly SEC filing where large investors disclose their U.S. stock holdings.",
  "13D": "SEC filing when an investor passes 5% of a company with activist intent (13G = the passive version).",
  "Lockup": "The ~180 days after an IPO when insiders can't sell. Expiry can flood the market with new supply.",
  "Hawkish / dovish": "Hawkish = leaning toward higher rates to fight inflation; dovish = leaning toward cuts to support growth.",
  "Short interest": "The % of shares sold short — a gauge of how many are betting the stock falls.",
  "Borrow fee": "The annual % cost to borrow a stock in order to short it. High = hard to short.",
  "Z-score": "How many standard deviations from normal — e.g. −2 is unusually cheap vs. its own history.",
  "Half-life": "How fast a stretched spread snaps back — the days for it to close half the gap to its mean. Shorter = quicker reversion.",
  "Hedge ratio": "How many shares of B to short per share of A so the pair is market-neutral (β from a regression of the two log-prices).",
  "Merger arb spread": "How far a takeover target trades BELOW the agreed deal value — the return you capture if the deal closes. A wide spread signals the market's doubt the deal completes.",
  "Sharpe": "Return earned per unit of risk taken. Higher is a better risk-adjusted result.",
  "Max drawdown": "The worst peak-to-trough drop over the period — the deepest loss you'd have sat through.",
  // Executive compensation (proxy statement)
  "NEO": "Named executive officer — the CEO, CFO and next-highest-paid execs whose pay the proxy must disclose.",
  "Bonus metrics": "The performance measures the annual cash bonus is scored on (e.g. EPS, revenue), with each measure's weight.",
  "PSU": "Performance stock unit — shares that only vest if multi-year goals (e.g. relative TSR, EPS growth) are hit.",
  "Non-equity incentive": "The annual cash bonus actually EARNED under the formula plan — the column most 'bonus' money sits in.",
  "Perquisites": "Extra personal benefits the company pays for — aircraft use, security, financial planning, club dues.",
  "Say-on-pay": "The shareholder vote approving executive pay. Support below ~90% is a warning; below 70% is a revolt.",
  "TSR": "Total shareholder return — price change plus dividends. 'Relative TSR' compares it to an index or peer group.",
  // Capital return
  "Shareholder yield": "Buybacks + dividends returned to owners in a year, as a % of market value — the total cash a company hands back.",
  "Buyback yield": "Cash spent repurchasing stock over the past year ÷ market value. How much of itself the company bought back.",
  "Net share count change": "The year-over-year change in shares outstanding. Negative = the count actually shrank (real, per-share-accretive); positive = buybacks are losing to stock-comp dilution.",
  "Payout / FCF": "Buybacks + dividends ÷ free cash flow. Above 1 means the company returns more than it earns — funded from the balance sheet or debt.",
};
