/**
 * Two-entity spin preview — "run a report on the two, now that we have the analyst-day information."
 * A spin splits one company into TWO investable entities, but a Form 10 is written entirely from the
 * SpinCo's perspective and the RemainCo never files one — so the single-entity briefing structurally
 * can't answer "products vs distribution." This preview fuses THREE sources into one side-by-side
 * read: the SpinCo's Form 10, the PARENT's own 10-K (where the to-be-spun segment's financials
 * actually live), and — when notes are ingested in the Research Desk — the sell-side/analyst-day
 * corpus on the parent (which is where standalone economics like ROE/inventory-turn framing live;
 * filings rarely state them). CLIENT-SAFE: types only. Generated by /api/spinoff-preview/[cik].
 */

export interface SpinEntity {
  name: string;
  ticker: string | null;
  role: "remainco" | "spinco";
  whatItIs: string | null; // the business in plain terms
  financials: string | null; // standalone/segment revenue + margin, verbatim-ish with the source labelled
  economics: string | null; // the business-model economics (margin structure, capital intensity, returns)
  whyOwnIt: string | null; // the case for owning THIS piece
  risks: string[]; // the 2-4 risks that most matter for this piece
}

export interface SpinMechanics {
  ratio: string | null; // distribution terms, verbatim-ish ("1 ADI share per 2 REZI shares")
  recordDate: string | null;
  distributionDate: string | null;
  whenIssued: string | null; // when-issued trading note if the filing states one
  note: string | null; // conditions / caveats
}

export interface TwoEntityPreview {
  cik: string;
  parent: { name: string; ticker: string | null };
  spinco: { name: string; ticker: string | null };
  sources: { label: string; url: string; date: string }[]; // the filings actually read
  // true = notes enriched the read · false = the corpus was checked and is EMPTY for this ticker ·
  // null = the corpus couldn't be checked (store slow/unreachable) — the UI must not claim "no notes
  // ingested" in the null case, only in the known-empty one.
  hasResearch: boolean | null;
  mechanics: SpinMechanics | null;
  remainco: SpinEntity | null;
  spincoEntity: SpinEntity | null;
  contrast: string | null; // the head-to-head economics read (the margins-vs-turns/ROE frame)
  watchItems: string[]; // what to track into and after the distribution
  researchRead: string | null; // what the ingested notes ADD beyond the filings (null without corpus)
  note?: string; // honest empty-state / failure reason
}

/** True when a preview carries enough to render. */
export function previewHasDetail(p: TwoEntityPreview | null): boolean {
  return !!p && !!(p.remainco?.whatItIs || p.spincoEntity?.whatItIs || p.contrast || p.mechanics?.ratio);
}
