// AUTO-GENERATED by scripts/gen-tracing-excludes.mjs — do not hand-edit.
// Per-route outputFileTracingExcludes: strips data/series/** and/or data/company/** from the
// serverless functions that DON'T read them, so Vercel functions stay well under the 250MB limit.
// Safe by construction: (1) only routes proven (import-graph) not to read a dir are listed; (2) every
// key is collision-checked against needing-routes under picomatch {contains:true}; (3) excludes only
// ever REMOVE already-included files (Next applies them after includes), so a stale/expanded route
// simply keeps the full data/ include. Regenerate: node scripts/gen-tracing-excludes.mjs --write
export const tracingExcludes = {
  "/api/ai-compare": [
    "./data/series/**"
  ],
  "/api/analyst-actions": [
    "./data/company/**"
  ],
  "/api/ask/*": [
    "./data/series/**"
  ],
  "/api/backtest-data/*": [
    "./data/company/**"
  ],
  "/api/borrow/*": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/briefing": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/briefing-news/*": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/catalyst-path/*": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/company-briefing/*": [
    "./data/series/**"
  ],
  "/api/compare-verdict": [
    "./data/series/**"
  ],
  "/api/compensation/*": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/docsearch": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/docsearch/snippet": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/earnings-call/*": [
    "./data/series/**"
  ],
  "/api/earnings-multiple/*": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/earnings-reaction/*": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/econ-series/*": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/exec-bios/*": [
    "./data/series/**"
  ],
  "/api/feedback": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/filing-summary/*": [
    "./data/series/**"
  ],
  "/api/filings/*": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/gamma/*": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/health/data": [
    "./data/series/**"
  ],
  "/api/industry-feed": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/industry-intraday": [
    "./data/company/**"
  ],
  "/api/insiders/*": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/intraday": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/iv-surface/*": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/market-headlines": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/market-pulse": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/news": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/news-tape": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/nl-screen": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/ohlc/*": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/options/*": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/portfolio/risk": [
    "./data/company/**"
  ],
  "/api/portfolio": [
    "./data/company/**"
  ],
  "/api/positioning/*": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/push-sub": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/quarterly-fundamentals/*": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/quote": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/ratings/*": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/reddit-buzz/*": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/redline/*": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/rel-valuation/*": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/research/actionable": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/research/health": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/research/pdf": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/research": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/research/search": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/research/synthesize": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/research/upload": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/risk-factors/*": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/search-index": [
    "./data/company/**"
  ],
  "/api/segment-economics/*": [
    "./data/series/**"
  ],
  "/api/segments/*": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/series/*": [
    "./data/company/**"
  ],
  "/api/shares/*": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/spinoff-report/*": [
    "./data/series/**"
  ],
  "/api/stocktwits/*": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/stocktwits-summary/*": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/transcript-analysis/*": [
    "./data/series/**"
  ],
  "/api/transcript-intel/*": [
    "./data/series/**"
  ],
  "/api/transcript-search/*": [
    "./data/series/**"
  ],
  "/api/transcript-text/*": [
    "./data/series/**"
  ],
  "/api/transcripts/*": [
    "./data/series/**"
  ],
  "/api/valuation-bands/*": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/api/vol-cone/*": [
    "./data/company/**"
  ],
  "/api/watchlist-digest": [
    "./data/series/**"
  ],
  "/api/watchlist-wire": [
    "./data/company/**"
  ],
  "/auth/callback": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/page.tsx": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/alerts": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/analyst-upside": [
    "./data/company/**"
  ],
  "/u/*/backtest": [
    "./data/company/**"
  ],
  "/u/*/binary-week": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/biotech-catalysts": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/biotech-vol": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/breadth": [
    "./data/company/**"
  ],
  "/u/*/briefing": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/buybacks": [
    "./data/company/**"
  ],
  "/u/*/campaigns": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/catalyst-calendar": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/catalyst-vol": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/cef": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/cef-hunter": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/chains": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/coiled": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/compare": [
    "./data/company/**"
  ],
  "/u/*/compare-stocks": [
    "./data/company/**"
  ],
  "/u/*/comps": [
    "./data/company/**"
  ],
  "/u/*/confluence": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/congress": [
    "./data/company/**"
  ],
  "/u/*/corp-events": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/covered-call": [
    "./data/company/**"
  ],
  "/u/*/credit-spreads": [
    "./data/company/**"
  ],
  "/u/*/debates": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/dispersion": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/distribution": [
    "./data/company/**"
  ],
  "/u/*/earnings": [
    "./data/company/**"
  ],
  "/u/*/earnings-desk": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/earnings-move": [
    "./data/company/**"
  ],
  "/u/*/earnings-odds": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/earnings-setup": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/earnings-week": [
    "./data/company/**"
  ],
  "/u/*/expectations": [
    "./data/company/**"
  ],
  "/u/*/factor-overlap": [
    "./data/company/**"
  ],
  "/u/*/fed": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/flow": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/forensics": [
    "./data/company/**"
  ],
  "/u/*/gamma-board": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/gov-contracts": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/guidance": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/guide": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/heatmap": [
    "./data/company/**"
  ],
  "/u/*/holdco-nav": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/holdco-nav/*": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/ideas": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/index/*": [
    "./data/company/**"
  ],
  "/u/*/insiders": [
    "./data/company/**"
  ],
  "/u/*/ipos": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/ipos/*": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/leaders": [
    "./data/company/**"
  ],
  "/u/*/lobbying": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/macro": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/market": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/merger-arb": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/morning-desk": [
    "./data/company/**"
  ],
  "/u/*/my-names": [
    "./data/company/**"
  ],
  "/u/*/news": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/overnight": [
    "./data/company/**"
  ],
  "/u/*/pairs": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/pead": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/policy": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/portfolio": [
    "./data/company/**"
  ],
  "/u/*/portfolio-income": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/portfolio-radar": [
    "./data/company/**"
  ],
  "/u/*/positioning": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/preview-record": [
    "./data/company/**"
  ],
  "/u/*/put-writing": [
    "./data/company/**"
  ],
  "/u/*/rates": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/ratio": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/reddit-buzz": [
    "./data/company/**"
  ],
  "/u/*/research": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/research-desk": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/revisions": [
    "./data/company/**"
  ],
  "/u/*/rotation": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/screener": [
    "./data/company/**"
  ],
  "/u/*/sector/*/compare": [
    "./data/company/**"
  ],
  "/u/*/sector/*": [
    "./data/company/**"
  ],
  "/u/*/sector/*/*": [
    "./data/company/**"
  ],
  "/u/*/short-mechanics": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/signal-record": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/skew": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/smart-money": [
    "./data/company/**"
  ],
  "/u/*/spac-arb": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/spinoffs": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/squeeze": [
    "./data/company/**"
  ],
  "/u/*/staples-scanner": [
    "./data/series/**"
  ],
  "/u/*/status": [
    "./data/series/**"
  ],
  "/u/*/stock/*/financials": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/superinvestors": [
    "./data/company/**"
  ],
  "/u/*/tenders": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/term-structure": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/track-record": [
    "./data/company/**"
  ],
  "/u/*/trade-desk": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/trump-stocks": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/valuation-history": [
    "./data/company/**"
  ],
  "/u/*/vol-cone": [
    "./data/company/**"
  ],
  "/u/*/vol-dislocation": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/warnings": [
    "./data/series/**",
    "./data/company/**"
  ],
  "/u/*/watchlist": [
    "./data/company/**"
  ],
  "/u/*/wire": [
    "./data/series/**",
    "./data/company/**"
  ]
};
